[extend]
  useDefault = true

[[rules]]
  id = "langfuse-project-public-key"
  description = "Langfuse project public key"
  regex = '''pk-lf-(?:ods-)?[0-9a-f]+\b'''
  keywords = ["pk-lf-"]

[[rules]]
  id = "langfuse-project-secret-key"
  description = "Langfuse project secret key"
  regex = '''sk-lf-(?:ods-)?[0-9a-f]+\b'''
  keywords = ["sk-lf-"]
